---
- name: Prepare VM for GitHub Runner
  hosts: runner
  become: true
  vars:
    github_token: ""
  
  tasks:

    - name: Ping
      ping:

    - name: Install required packages
      ansible.builtin.apt:
        name: ['git', 'curl', 'jq', 'dotnet-sdk-8.0']
        state: present
      become: true

    - name: Download GitHub Runner
      ansible.builtin.get_url:
        url: "https://github.com/actions/runner/releases/download/v2.316.1/actions-runner-osx-x64-2.316.1.tar.gz"
        dest: /home/azureadmin/actions-runner-linux-x64.tar.gz
        mode: 0644

    - name: Extract GitHub Runner
      ansible.builtin.unarchive:
        src: /home/azureadmin/actions-runner-linux-x64.tar.gz
        dest: /home/azureadmin
        remote_src: yes

    - name: Configure GitHub Runner
      command: |
        "/home/azureadmin/config.sh --url https://github.com/theonorg/echo-app --token ${{ github_token }}"

    - name: Install GitHub Runner as a service
      systemd:
        name: actions.runner.your_vm_host
        state: started
        enabled: yes
        daemon_reload: yes
        user: azureadmin
        exec_start: /home/github-runner/run.sh
      become: true