---
- name: Prepare VM for GitHub Runner
  hosts: runner
  become: true
  vars:
    github_token: ""
  
  tasks:

    - name: Ping
      ping:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: true

    - name: Install required packages
      ansible.builtin.apt:
        name: ['git', 'curl', 'jq', 'dotnet-sdk-8.0']
        state: present
      become: true

    - name: Create runner directory
      ansible.buitin.file:
        path: /home/azureadmin/runner
        state: directory
        mode: 0755
        owner: azureadmin
        group: azureadmin

    - name: Download GitHub Runner
      ansible.builtin.get_url:
        url: "https://github.com/actions/runner/releases/download/v2.316.1/actions-runner-osx-x64-2.316.1.tar.gz"
        dest: /home/azureadmin/runner/actions-runner-linux-x64.tar.gz
        mode: 0644

    - name: Extract GitHub Runner
      ansible.builtin.unarchive:
        src: /home/azureadmin/runner/actions-runner-linux-x64.tar.gz
        dest: /home/azureadmin/runner
        remote_src: yes

    - name: Configure GitHub Runner
      ansible.builtin.command: |
        cd /home/azureadmin/runner
        ls -la
        "./config.sh --url https://github.com/theonorg/echo-app --token ${{ github_token }}"

    - name: Install GitHub Runner as a service
      ansible.builtin.systemd:
        name: actions.runner.your_vm_host
        state: started
        enabled: yes
        daemon_reload: yes
        user: azureadmin
        exec_start: /home/azureadmin/runner/run.sh
      become: true